In [2]:
import os
import requests
import json
import pandas as pd

In [3]:
fsq_api_key = os.environ['FOURSQUARE_API']

In [100]:
#import lat long data from city bikes as an input to foursquare and yelp APIs

city_bike_url = "https://api.citybik.es/v2/networks/mobibikes"
response = requests.request("GET",city_bike_url)
data = response.json()
stations = data['network']['stations']
van_station_df = pd.json_normalize(data = stations)
van_station_df.dropna(subset=['latitude', 'longitude'], inplace=True)
van_station_df['lat_long'] = van_station_df['latitude'].astype(str) + ',' + van_station_df['longitude'].astype(str)
van_station_df = van_station_df[van_station_df['lat_long'] != '0.0,0.0']
# van_station_df

In [104]:
lat_long = van_station_df.lat_long.tolist()

In [103]:
lat = van_station_df.latitude.tolist()
long = van_station_df.longitude.tolist()

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [88]:
fsq_url = "https://api.foursquare.com/v3/places/search"
fsq_headers = {
    'Accept': "application/json",
    "Authorization": fsq_api_key
}

fsq_bar_df = pd.DataFrame()
fsq_bar_dict= {}

for i in locations:
    fsq_params = {
        "categories": '13003', #bars 13003, cafes 13032, tattoo shop 11075, restaurant 13065, parks 16032
        "ll": i,
        "radius": '500',
        "limit":'50'
    }

    response = requests.request("GET",fsq_url, params=fsq_params,headers=fsq_headers)
    data = response.json()
    fsq_bar_dict[i] = len(data['results'])
    
    fsq_df = pd.json_normalize(data = data['results'])
    fsq_bar_df = pd.concat([fsq_bar_df, fsq_df])

print(fsq_bar_dict)      
# fsq_bar_df

{'49.262487,-123.114397': 5, '49.274566,-123.121817': 50, '49.279764,-123.110154': 40, '49.260599,-123.113504': 4, '49.264215,-123.117772': 7, '49.270877,-123.115103': 7, '49.26893,-123.11813': 6, '49.271721,-123.104207': 6, '49.287214,-123.11287': 34, '49.282409,-123.118541': 47, '49.287097,-123.118551': 36, '49.273471,-123.118016': 34, '49.282758,-123.122092': 50, '49.286042,-123.113176': 42, '49.28602,-123.116624': 47, '49.279739,-123.116251': 50, '49.277483,-123.114279': 28, '49.275679,-123.116963': 38, '49.282759,-123.106955': 50, '49.288444,-123.139203': 12, '49.289124,-123.12196': 23, '49.28062,-123.12482': 46, '49.279938,-123.127478': 50, '49.273663,-123.127075': 35, '49.28972,-123.144028': 12, '49.285253,-123.134356': 11, '49.283343,-123.131099': 18, '49.284605,-123.108662': 50, '49.279821,-123.10802': 50, '49.278004,-123.105664': 22, '49.279342,-123.101822': 39, '49.273833,-123.114373': 11, '49.28526,-123.141809': 10, '49.281506,-123.120101': 50, '49.276115,-123.114496': 29, '49.272827,-123.147744': 3, '49.269361,-123.13782': 7, '49.2653,-123.13811': 6, '49.262598,-123.138921': 7, '49.25894,-123.139272': 3, '49.258763,-123.115392': 4, '49.266724,-123.104824': 15, '49.262141,-123.101961': 20, '49.268269,-123.147885': 8, '49.275717,-123.142564': 0, '49.276436,-123.11877': 50, '49.277844,-123.120942': 50, '49.265089,-123.119425': 7, '49.28026,-123.135244': 7, '49.291909,-123.140713': 4, '49.293257,-123.138563': 2, '49.288011,-123.132006': 6, '49.28117,-123.104419': 50, '49.283227,-123.120523': 50, '49.299292,-123.130281': 0, '49.29534,-123.150433': 1, '49.294318,-123.148808': 1, '49.298657,-123.121176': 0, '49.259183,-123.120126': 2, '49.263837,-123.105173': 14, '49.270721,-123.146175': 6, '49.265605,-123.152566': 7, '49.267222,-123.153157': 11, '49.262255,-123.126217': 2, '49.257654,-123.153212': 0, '49.25919,-123.148268': 0, '49.25741,-123.148531': 0, '49.285953,-123.124066': 32, '49.280881,-123.130672': 16, '49.256845,-123.120071': 3, '49.25849,-123.104799': 10, '49.258425,-123.100792': 15, '49.270905,-123.126006': 10, '49.273568,-123.129935': 21, '49.277141,-123.122589': 50, '49.267859,-123.145782': 9, '49.265336,-123.145823': 9, '49.267628,-123.127698': 1, '49.275938,-123.145939': 2, '49.2756,-123.102661': 14, '49.284157,-123.099917': 38, '49.258924,-123.152591': 0, '49.266774,-123.141135': 7, '49.273355,-123.154493': 8, '49.276144,-123.151272': 2, '49.268339,-123.157443': 11, '49.284062,-123.095097': 7, '49.261742,-123.13148': 3, '49.262206,-123.109091': 4, '49.27023,-123.10651': 8, '49.262062,-123.104656': 15, '49.27033,-123.10275': 5, '49.258902,-123.109596': 0, '49.282224,-123.132778': 10, '49.265071,-123.123864': 4, '49.265198,-123.131043': 1, '49.273691,-123.102232': 9, '49.2685027,-123.0975014': 5, '49.278529,-123.100017': 18, '49.288682,-123.11818': 24, '49.258864,-123.14353': 1, '49.271741,-123.155421': 8, '49.262822,-123.14338': 10, '49.263635,-123.099236': 18, '49.28763,-123.127245': 19, '49.297933,-123.130758': 1, '49.258819,-123.131317': 0, '49.280284,-123.097052': 18, '49.276294,-123.106534': 10, '49.277469,-123.081315': 2, '49.277665,-123.073653': 3, '49.277436,-123.070427': 3, '49.280332,-123.070068': 9, '49.279369,-123.091241': 6, '49.283992,-123.091206': 7, '49.274881,-123.069323': 7, '49.275882,-123.071865': 5, '49.273777,-123.092723': 3, '49.265005,-123.079481': 0, '49.265024,-123.08127': 0, '49.271377,-123.069416': 10, '49.268616,-123.069908': 10, '49.266969,-123.069936': 9, '49.263242,-123.070521': 4, '49.261403,-123.070102': 4, '49.261263,-123.073707': 3, '49.262242,-123.081459': 0, '49.262321,-123.09306': 9, '49.264251,-123.073853': 3, '49.266751,-123.073501': 7, '49.270684,-123.073562': 9, '49.2731,-123.0732': 10, '49.254667,-123.101389': 7, '49.256694,-123.096579': 12, '49.258352,-123.096337': 16, '49.258817,-123.092797': 8, '49.26151,-123.089413': 3, '49.263382,-123.088837': 2, '49.261353,-123.085333': 1, '49.264466,-123.085183': 1, '49.280197,-123.065859': 3, '49.266725,-123.065925': 7, '49.261188,-123.066009': 3, '49.256857,-123.065646': 1, '49.283986,-123.065264': 7, '49.257985,-123.083366': 0, '49.257939,-123.089531': 4, '49.256496,-123.075426': 0, '49.283236,-123.070443': 10, '49.267266,-123.090786': 0, '49.265242,-123.095577': 11, '49.265213,-123.090785': 2, '49.302577,-123.155616': 0, '49.277595,-123.09583': 17, '49.279235,-123.087528': 5, '49.277333,-123.087359': 6, '49.273103,-123.069892': 9, '49.261973,-123.09725': 20, '49.275295,-123.132585': 12, '49.285871,-123.12105': 37, '49.284893,-123.128685': 22, '49.263962,-123.112621': 9, '49.277615,-123.091654': 5, '49.282214,-123.114101': 48, '49.266456,-123.100324': 11, '49.268216,-123.103168': 11, '49.284554,-123.111031': 50, '49.280216,-123.117639': 50, '49.266314,-123.116011': 12, '49.280852,-123.084746': 5, '49.285512,-123.1384': 11, '49.27821,-123.136972': 9, '49.281301,-123.139108': 5, '49.283298,-123.142288': 9, '49.280787,-123.115271': 36, '49.266476,-123.109389': 9, '49.290587,-123.13625': 2, '49.312568,-123.144177': 0, '49.262835,-123.152626': 4, '49.256825,-123.105234': 7, '49.275683,-123.124388': 50, '49.263518,-123.09568': 18, '49.28691,-123.128818': 14, '49.282503,-123.124697': 50, '49.283749,-123.136133': 10, '49.262944,-123.148109': 6, '49.27029,-123.135025': 6, '49.280427,-123.074082': 6, '49.279259,-123.119145': 50, '49.285836,-123.127265': 21, '49.272969,-123.164325': 0, '49.27247,-123.185643': 2, '49.271471,-123.17731': 1, '49.290112,-123.127062': 13, '49.263523,-123.155267': 4, '49.264928,-123.168068': 6, '49.264483,-123.173926': 5, '49.264579,-123.18373': 4, '49.263746,-123.069892': 4, '49.258761,-123.127071': 0, '49.268974,-123.190701': 2, '49.273011,-123.159663': 5, '49.266924,-123.173849': 8, '49.264326,-123.164725': 1, '49.266636,-123.183661': 3, '49.254818,-123.114785': 3, '49.268837,-123.177633': 3, '49.255034,-123.120226': 3, '49.271044,-123.170661': 2, '49.252691,-123.101289': 6, '49.272172,-123.097978': 7, '49.271082,-123.191458': 0, '49.27808,-123.130557': 29, '49.269969,-123.109623': 8, '49.287528,-123.142139': 12, '49.28803,-123.142135': 12, '49.259579,-123.114769': 6, '49.2890705989865,-123.138407369468': 11, '49.287782,-123.12395': 23, '49.28512,-123.11242': 47, '49.247854,-123.153422': 1, '49.265939,-123.1129': 10, '49.261122,-123.097571': 19, '49.267725,-123.11311': 11, '49.245135,-123.116098': 0, '49.274232,-123.129998': 24, '49.238105,-123.154966': 1, '49.246243,-123.124373': 0, '49.249722,-123.104991': 7, '49.243375,-123.104978': 4, '49.282087,-123.056909': 2, '49.283968,-123.061615': 3, '49.287464,-123.060771': 3, '49.285575,-123.061575': 3, '49.251358,-123.115637': 3, '49.249184,-123.116141': 0, '49.245535,-123.120496': 0, '49.289255,-123.132677': 8, '49.252656,-123.067965': 0, '49.277527,-123.129464': 33, '49.259469,-123.145718': 2}

In [89]:
fsq_url = "https://api.foursquare.com/v3/places/search"
fsq_headers = {
    'Accept': "application/json",
    "Authorization": fsq_api_key
}

fsq_tattoo_df = pd.DataFrame()
fsq_tattoo_dict= {}

for i in locations:
    fsq_params = {
        "categories": '11075', #bars 13003, cafes 13032, tattoo shop 11075, restaurant 13065, parks 16032
        "ll": i,
        "radius": '500',
        "limit":'50'
    }

    response = requests.request("GET",fsq_url, params=fsq_params,headers=fsq_headers)
    data = response.json()
    fsq_tattoo_dict[i] = len(data['results'])
    
    fsq_df = pd.json_normalize(data = data['results'])
    fsq_tattoo_df = pd.concat([fsq_tattoo_df, fsq_df])

print(fsq_tattoo_dict)      
# fsq_tattoo_df

{'49.262487,-123.114397': 3, '49.274566,-123.121817': 6, '49.279764,-123.110154': 5, '49.260599,-123.113504': 2, '49.264215,-123.117772': 0, '49.270877,-123.115103': 0, '49.26893,-123.11813': 0, '49.271721,-123.104207': 0, '49.287214,-123.11287': 2, '49.282409,-123.118541': 4, '49.287097,-123.118551': 0, '49.273471,-123.118016': 1, '49.282758,-123.122092': 5, '49.286042,-123.113176': 4, '49.28602,-123.116624': 3, '49.279739,-123.116251': 3, '49.277483,-123.114279': 1, '49.275679,-123.116963': 1, '49.282759,-123.106955': 7, '49.288444,-123.139203': 0, '49.289124,-123.12196': 0, '49.28062,-123.12482': 6, '49.279938,-123.127478': 5, '49.273663,-123.127075': 2, '49.28972,-123.144028': 0, '49.285253,-123.134356': 0, '49.283343,-123.131099': 0, '49.284605,-123.108662': 6, '49.279821,-123.10802': 4, '49.278004,-123.105664': 4, '49.279342,-123.101822': 8, '49.273833,-123.114373': 0, '49.28526,-123.141809': 0, '49.281506,-123.120101': 6, '49.276115,-123.114496': 1, '49.272827,-123.147744': 0, '49.269361,-123.13782': 0, '49.2653,-123.13811': 0, '49.262598,-123.138921': 0, '49.25894,-123.139272': 1, '49.258763,-123.115392': 1, '49.266724,-123.104824': 3, '49.262141,-123.101961': 4, '49.268269,-123.147885': 4, '49.275717,-123.142564': 0, '49.276436,-123.11877': 4, '49.277844,-123.120942': 7, '49.265089,-123.119425': 0, '49.28026,-123.135244': 0, '49.291909,-123.140713': 0, '49.293257,-123.138563': 0, '49.288011,-123.132006': 0, '49.28117,-123.104419': 7, '49.283227,-123.120523': 2, '49.299292,-123.130281': 0, '49.29534,-123.150433': 0, '49.294318,-123.148808': 0, '49.298657,-123.121176': 0, '49.259183,-123.120126': 1, '49.263837,-123.105173': 4, '49.270721,-123.146175': 4, '49.265605,-123.152566': 3, '49.267222,-123.153157': 3, '49.262255,-123.126217': 1, '49.257654,-123.153212': 0, '49.25919,-123.148268': 0, '49.25741,-123.148531': 0, '49.285953,-123.124066': 0, '49.280881,-123.130672': 0, '49.256845,-123.120071': 1, '49.25849,-123.104799': 0, '49.258425,-123.100792': 1, '49.270905,-123.126006': 0, '49.273568,-123.129935': 0, '49.277141,-123.122589': 6, '49.267859,-123.145782': 4, '49.265336,-123.145823': 4, '49.267628,-123.127698': 1, '49.275938,-123.145939': 0, '49.2756,-123.102661': 2, '49.284157,-123.099917': 5, '49.258924,-123.152591': 0, '49.266774,-123.141135': 1, '49.273355,-123.154493': 1, '49.276144,-123.151272': 0, '49.268339,-123.157443': 1, '49.284062,-123.095097': 3, '49.261742,-123.13148': 1, '49.262206,-123.109091': 3, '49.27023,-123.10651': 0, '49.262062,-123.104656': 5, '49.27033,-123.10275': 0, '49.258902,-123.109596': 2, '49.282224,-123.132778': 0, '49.265071,-123.123864': 1, '49.265198,-123.131043': 1, '49.273691,-123.102232': 1, '49.2685027,-123.0975014': 0, '49.278529,-123.100017': 6, '49.288682,-123.11818': 0, '49.258864,-123.14353': 1, '49.271741,-123.155421': 1, '49.262822,-123.14338': 0, '49.263635,-123.099236': 4, '49.28763,-123.127245': 0, '49.297933,-123.130758': 0, '49.258819,-123.131317': 0, '49.280284,-123.097052': 6, '49.276294,-123.106534': 0, '49.277469,-123.081315': 0, '49.277665,-123.073653': 3, '49.277436,-123.070427': 3, '49.280332,-123.070068': 3, '49.279369,-123.091241': 2, '49.283992,-123.091206': 1, '49.274881,-123.069323': 3, '49.275882,-123.071865': 3, '49.273777,-123.092723': 0, '49.265005,-123.079481': 0, '49.265024,-123.08127': 0, '49.271377,-123.069416': 2, '49.268616,-123.069908': 2, '49.266969,-123.069936': 1, '49.263242,-123.070521': 0, '49.261403,-123.070102': 0, '49.261263,-123.073707': 0, '49.262242,-123.081459': 0, '49.262321,-123.09306': 2, '49.264251,-123.073853': 0, '49.266751,-123.073501': 1, '49.270684,-123.073562': 2, '49.2731,-123.0732': 2, '49.254667,-123.101389': 1, '49.256694,-123.096579': 1, '49.258352,-123.096337': 0, '49.258817,-123.092797': 2, '49.26151,-123.089413': 0, '49.263382,-123.088837': 0, '49.261353,-123.085333': 0, '49.264466,-123.085183': 0, '49.280197,-123.065859': 4, '49.266725,-123.065925': 1, '49.261188,-123.066009': 0, '49.256857,-123.065646': 0, '49.283986,-123.065264': 1, '49.257985,-123.083366': 0, '49.257939,-123.089531': 2, '49.256496,-123.075426': 0, '49.283236,-123.070443': 1, '49.267266,-123.090786': 0, '49.265242,-123.095577': 3, '49.265213,-123.090785': 0, '49.302577,-123.155616': 0, '49.277595,-123.09583': 4, '49.279235,-123.087528': 1, '49.277333,-123.087359': 1, '49.273103,-123.069892': 3, '49.261973,-123.09725': 3, '49.275295,-123.132585': 0, '49.285871,-123.12105': 1, '49.284893,-123.128685': 0, '49.263962,-123.112621': 2, '49.277615,-123.091654': 1, '49.282214,-123.114101': 5, '49.266456,-123.100324': 4, '49.268216,-123.103168': 0, '49.284554,-123.111031': 5, '49.280216,-123.117639': 5, '49.266314,-123.116011': 1, '49.280852,-123.084746': 1, '49.285512,-123.1384': 0, '49.27821,-123.136972': 0, '49.281301,-123.139108': 0, '49.283298,-123.142288': 0, '49.280787,-123.115271': 5, '49.266476,-123.109389': 2, '49.290587,-123.13625': 0, '49.312568,-123.144177': 0, '49.262835,-123.152626': 0, '49.256825,-123.105234': 1, '49.275683,-123.124388': 6, '49.263518,-123.09568': 3, '49.28691,-123.128818': 0, '49.282503,-123.124697': 4, '49.283749,-123.136133': 0, '49.262944,-123.148109': 0, '49.27029,-123.135025': 0, '49.280427,-123.074082': 2, '49.279259,-123.119145': 6, '49.285836,-123.127265': 0, '49.272969,-123.164325': 0, '49.27247,-123.185643': 1, '49.271471,-123.17731': 0, '49.290112,-123.127062': 0, '49.263523,-123.155267': 0, '49.264928,-123.168068': 1, '49.264483,-123.173926': 1, '49.264579,-123.18373': 2, '49.263746,-123.069892': 0, '49.258761,-123.127071': 0, '49.268974,-123.190701': 0, '49.273011,-123.159663': 1, '49.266924,-123.173849': 0, '49.264326,-123.164725': 1, '49.266636,-123.183661': 2, '49.254818,-123.114785': 1, '49.268837,-123.177633': 1, '49.255034,-123.120226': 0, '49.271044,-123.170661': 0, '49.252691,-123.101289': 1, '49.272172,-123.097978': 1, '49.271082,-123.191458': 0, '49.27808,-123.130557': 4, '49.269969,-123.109623': 1, '49.287528,-123.142139': 0, '49.28803,-123.142135': 0, '49.259579,-123.114769': 1, '49.2890705989865,-123.138407369468': 0, '49.287782,-123.12395': 0, '49.28512,-123.11242': 5, '49.247854,-123.153422': 0, '49.265939,-123.1129': 2, '49.261122,-123.097571': 3, '49.267725,-123.11311': 1, '49.245135,-123.116098': 0, '49.274232,-123.129998': 2, '49.238105,-123.154966': 0, '49.246243,-123.124373': 0, '49.249722,-123.104991': 0, '49.243375,-123.104978': 1, '49.282087,-123.056909': 2, '49.283968,-123.061615': 2, '49.287464,-123.060771': 0, '49.285575,-123.061575': 0, '49.251358,-123.115637': 0, '49.249184,-123.116141': 0, '49.245535,-123.120496': 0, '49.289255,-123.132677': 0, '49.252656,-123.067965': 0, '49.277527,-123.129464': 5, '49.259469,-123.145718': 0}

In [90]:
fsq_url = "https://api.foursquare.com/v3/places/search"
fsq_headers = {
    'Accept': "application/json",
    "Authorization": fsq_api_key
}

fsq_cafe_df = pd.DataFrame()
fsq_cafe_dict= {}

for i in locations:
    fsq_params = {
        "categories": '13032', #bars 13003, cafes 13032, tattoo shop 11075, restaurant 13065, parks 16032
        "ll": i,
        "radius": '500',
        "limit":'50'
    }

    response = requests.request("GET",fsq_url, params=fsq_params,headers=fsq_headers)
    data = response.json()
    fsq_cafe_dict[i] = len(data['results'])
    
    fsq_df = pd.json_normalize(data = data['results'])
    fsq_cafe_df = pd.concat([fsq_cafe_df, fsq_df])

print(fsq_cafe_dict)      
# fsq_cafe_df

{'49.262487,-123.114397': 25, '49.274566,-123.121817': 24, '49.279764,-123.110154': 50, '49.260599,-123.113504': 18, '49.264215,-123.117772': 26, '49.270877,-123.115103': 6, '49.26893,-123.11813': 6, '49.271721,-123.104207': 13, '49.287214,-123.11287': 50, '49.282409,-123.118541': 50, '49.287097,-123.118551': 50, '49.273471,-123.118016': 21, '49.282758,-123.122092': 46, '49.286042,-123.113176': 50, '49.28602,-123.116624': 50, '49.279739,-123.116251': 50, '49.277483,-123.114279': 34, '49.275679,-123.116963': 40, '49.282759,-123.106955': 47, '49.288444,-123.139203': 23, '49.289124,-123.12196': 40, '49.28062,-123.12482': 29, '49.279938,-123.127478': 34, '49.273663,-123.127075': 20, '49.28972,-123.144028': 11, '49.285253,-123.134356': 17, '49.283343,-123.131099': 29, '49.284605,-123.108662': 50, '49.279821,-123.10802': 45, '49.278004,-123.105664': 32, '49.279342,-123.101822': 37, '49.273833,-123.114373': 10, '49.28526,-123.141809': 10, '49.281506,-123.120101': 50, '49.276115,-123.114496': 31, '49.272827,-123.147744': 8, '49.269361,-123.13782': 21, '49.2653,-123.13811': 12, '49.262598,-123.138921': 11, '49.25894,-123.139272': 4, '49.258763,-123.115392': 10, '49.266724,-123.104824': 23, '49.262141,-123.101961': 22, '49.268269,-123.147885': 19, '49.275717,-123.142564': 1, '49.276436,-123.11877': 46, '49.277844,-123.120942': 50, '49.265089,-123.119425': 23, '49.28026,-123.135244': 9, '49.291909,-123.140713': 14, '49.293257,-123.138563': 11, '49.288011,-123.132006': 40, '49.28117,-123.104419': 50, '49.283227,-123.120523': 50, '49.299292,-123.130281': 2, '49.29534,-123.150433': 0, '49.294318,-123.148808': 0, '49.298657,-123.121176': 0, '49.259183,-123.120126': 14, '49.263837,-123.105173': 24, '49.270721,-123.146175': 21, '49.265605,-123.152566': 23, '49.267222,-123.153157': 20, '49.262255,-123.126217': 17, '49.257654,-123.153212': 2, '49.25919,-123.148268': 4, '49.25741,-123.148531': 1, '49.285953,-123.124066': 46, '49.280881,-123.130672': 27, '49.256845,-123.120071': 11, '49.25849,-123.104799': 9, '49.258425,-123.100792': 11, '49.270905,-123.126006': 8, '49.273568,-123.129935': 22, '49.277141,-123.122589': 50, '49.267859,-123.145782': 20, '49.265336,-123.145823': 14, '49.267628,-123.127698': 6, '49.275938,-123.145939': 4, '49.2756,-123.102661': 15, '49.284157,-123.099917': 23, '49.258924,-123.152591': 3, '49.266774,-123.141135': 19, '49.273355,-123.154493': 4, '49.276144,-123.151272': 4, '49.268339,-123.157443': 14, '49.284062,-123.095097': 9, '49.261742,-123.13148': 7, '49.262206,-123.109091': 15, '49.27023,-123.10651': 12, '49.262062,-123.104656': 23, '49.27033,-123.10275': 18, '49.258902,-123.109596': 7, '49.282224,-123.132778': 14, '49.265071,-123.123864': 19, '49.265198,-123.131043': 8, '49.273691,-123.102232': 7, '49.2685027,-123.0975014': 16, '49.278529,-123.100017': 25, '49.288682,-123.11818': 43, '49.258864,-123.14353': 3, '49.271741,-123.155421': 13, '49.262822,-123.14338': 10, '49.263635,-123.099236': 15, '49.28763,-123.127245': 42, '49.297933,-123.130758': 2, '49.258819,-123.131317': 4, '49.280284,-123.097052': 26, '49.276294,-123.106534': 13, '49.277469,-123.081315': 7, '49.277665,-123.073653': 11, '49.277436,-123.070427': 10, '49.280332,-123.070068': 12, '49.279369,-123.091241': 14, '49.283992,-123.091206': 6, '49.274881,-123.069323': 12, '49.275882,-123.071865': 15, '49.273777,-123.092723': 6, '49.265005,-123.079481': 2, '49.265024,-123.08127': 2, '49.271377,-123.069416': 16, '49.268616,-123.069908': 16, '49.266969,-123.069936': 13, '49.263242,-123.070521': 10, '49.261403,-123.070102': 5, '49.261263,-123.073707': 4, '49.262242,-123.081459': 2, '49.262321,-123.09306': 5, '49.264251,-123.073853': 9, '49.266751,-123.073501': 12, '49.270684,-123.073562': 14, '49.2731,-123.0732': 14, '49.254667,-123.101389': 8, '49.256694,-123.096579': 10, '49.258352,-123.096337': 10, '49.258817,-123.092797': 6, '49.26151,-123.089413': 5, '49.263382,-123.088837': 6, '49.261353,-123.085333': 3, '49.264466,-123.085183': 4, '49.280197,-123.065859': 7, '49.266725,-123.065925': 12, '49.261188,-123.066009': 5, '49.256857,-123.065646': 3, '49.283986,-123.065264': 7, '49.257985,-123.083366': 3, '49.257939,-123.089531': 6, '49.256496,-123.075426': 1, '49.283236,-123.070443': 6, '49.267266,-123.090786': 6, '49.265242,-123.095577': 17, '49.265213,-123.090785': 5, '49.302577,-123.155616': 0, '49.277595,-123.09583': 22, '49.279235,-123.087528': 8, '49.277333,-123.087359': 6, '49.273103,-123.069892': 15, '49.261973,-123.09725': 19, '49.275295,-123.132585': 18, '49.285871,-123.12105': 50, '49.284893,-123.128685': 34, '49.263962,-123.112621': 24, '49.277615,-123.091654': 9, '49.282214,-123.114101': 50, '49.266456,-123.100324': 22, '49.268216,-123.103168': 17, '49.284554,-123.111031': 50, '49.280216,-123.117639': 48, '49.266314,-123.116011': 21, '49.280852,-123.084746': 8, '49.285512,-123.1384': 15, '49.27821,-123.136972': 7, '49.281301,-123.139108': 5, '49.283298,-123.142288': 5, '49.280787,-123.115271': 50, '49.266476,-123.109389': 21, '49.290587,-123.13625': 24, '49.312568,-123.144177': 1, '49.262835,-123.152626': 8, '49.256825,-123.105234': 7, '49.275683,-123.124388': 32, '49.263518,-123.09568': 14, '49.28691,-123.128818': 39, '49.282503,-123.124697': 45, '49.283749,-123.136133': 10, '49.262944,-123.148109': 6, '49.27029,-123.135025': 18, '49.280427,-123.074082': 6, '49.279259,-123.119145': 50, '49.285836,-123.127265': 39, '49.272969,-123.164325': 0, '49.27247,-123.185643': 3, '49.271471,-123.17731': 1, '49.290112,-123.127062': 36, '49.263523,-123.155267': 8, '49.264928,-123.168068': 16, '49.264483,-123.173926': 14, '49.264579,-123.18373': 7, '49.263746,-123.069892': 11, '49.258761,-123.127071': 5, '49.268974,-123.190701': 3, '49.273011,-123.159663': 2, '49.266924,-123.173849': 14, '49.264326,-123.164725': 12, '49.266636,-123.183661': 7, '49.254818,-123.114785': 10, '49.268837,-123.177633': 4, '49.255034,-123.120226': 9, '49.271044,-123.170661': 4, '49.252691,-123.101289': 5, '49.272172,-123.097978': 13, '49.271082,-123.191458': 1, '49.27808,-123.130557': 28, '49.269969,-123.109623': 11, '49.287528,-123.142139': 13, '49.28803,-123.142135': 13, '49.259579,-123.114769': 19, '49.2890705989865,-123.138407369468': 26, '49.287782,-123.12395': 50, '49.28512,-123.11242': 50, '49.247854,-123.153422': 1, '49.265939,-123.1129': 23, '49.261122,-123.097571': 18, '49.267725,-123.11311': 15, '49.245135,-123.116098': 1, '49.274232,-123.129998': 23, '49.238105,-123.154966': 16, '49.246243,-123.124373': 8, '49.249722,-123.104991': 10, '49.243375,-123.104978': 6, '49.282087,-123.056909': 11, '49.283968,-123.061615': 13, '49.287464,-123.060771': 2, '49.285575,-123.061575': 6, '49.251358,-123.115637': 11, '49.249184,-123.116141': 3, '49.245535,-123.120496': 5, '49.289255,-123.132677': 31, '49.252656,-123.067965': 3, '49.277527,-123.129464': 33, '49.259469,-123.145718': 3}

In [91]:
fsq_url = "https://api.foursquare.com/v3/places/search"
fsq_headers = {
    'Accept': "application/json",
    "Authorization": fsq_api_key
}

fsq_rest_df = pd.DataFrame()
fsq_rest_dict= {}

for i in locations:
    fsq_params = {
        "categories": '13065', #bars 13003, cafes 13032, tattoo shop 11075, restaurant 13065, parks 16032
        "ll": i,
        "radius": '500',
        "limit":'50'
    }

    response = requests.request("GET",fsq_url, params=fsq_params,headers=fsq_headers)
    data = response.json()
    fsq_rest_dict[i] = len(data['results'])
    
    fsq_df = pd.json_normalize(data = data['results'])
    fsq_rest_df = pd.concat([fsq_rest_df, fsq_df])

print(fsq_rest_dict)      
# fsq_cafe_df

{'49.262487,-123.114397': 47, '49.274566,-123.121817': 50, '49.279764,-123.110154': 50, '49.260599,-123.113504': 48, '49.264215,-123.117772': 50, '49.270877,-123.115103': 23, '49.26893,-123.11813': 18, '49.271721,-123.104207': 45, '49.287214,-123.11287': 50, '49.282409,-123.118541': 50, '49.287097,-123.118551': 50, '49.273471,-123.118016': 50, '49.282758,-123.122092': 50, '49.286042,-123.113176': 50, '49.28602,-123.116624': 50, '49.279739,-123.116251': 50, '49.277483,-123.114279': 50, '49.275679,-123.116963': 50, '49.282759,-123.106955': 50, '49.288444,-123.139203': 50, '49.289124,-123.12196': 50, '49.28062,-123.12482': 50, '49.279938,-123.127478': 50, '49.273663,-123.127075': 50, '49.28972,-123.144028': 43, '49.285253,-123.134356': 32, '49.283343,-123.131099': 50, '49.284605,-123.108662': 50, '49.279821,-123.10802': 50, '49.278004,-123.105664': 47, '49.279342,-123.101822': 50, '49.273833,-123.114373': 37, '49.28526,-123.141809': 41, '49.281506,-123.120101': 50, '49.276115,-123.114496': 50, '49.272827,-123.147744': 22, '49.269361,-123.13782': 50, '49.2653,-123.13811': 49, '49.262598,-123.138921': 50, '49.25894,-123.139272': 22, '49.258763,-123.115392': 30, '49.266724,-123.104824': 50, '49.262141,-123.101961': 50, '49.268269,-123.147885': 47, '49.275717,-123.142564': 4, '49.276436,-123.11877': 50, '49.277844,-123.120942': 50, '49.265089,-123.119425': 50, '49.28026,-123.135244': 43, '49.291909,-123.140713': 43, '49.293257,-123.138563': 41, '49.288011,-123.132006': 50, '49.28117,-123.104419': 50, '49.283227,-123.120523': 50, '49.299292,-123.130281': 1, '49.29534,-123.150433': 1, '49.294318,-123.148808': 3, '49.298657,-123.121176': 0, '49.259183,-123.120126': 38, '49.263837,-123.105173': 48, '49.270721,-123.146175': 43, '49.265605,-123.152566': 49, '49.267222,-123.153157': 45, '49.262255,-123.126217': 50, '49.257654,-123.153212': 2, '49.25919,-123.148268': 9, '49.25741,-123.148531': 1, '49.285953,-123.124066': 50, '49.280881,-123.130672': 43, '49.256845,-123.120071': 42, '49.25849,-123.104799': 30, '49.258425,-123.100792': 40, '49.270905,-123.126006': 31, '49.273568,-123.129935': 44, '49.277141,-123.122589': 50, '49.267859,-123.145782': 44, '49.265336,-123.145823': 47, '49.267628,-123.127698': 19, '49.275938,-123.145939': 15, '49.2756,-123.102661': 44, '49.284157,-123.099917': 46, '49.258924,-123.152591': 8, '49.266774,-123.141135': 50, '49.273355,-123.154493': 30, '49.276144,-123.151272': 19, '49.268339,-123.157443': 50, '49.284062,-123.095097': 20, '49.261742,-123.13148': 31, '49.262206,-123.109091': 25, '49.27023,-123.10651': 49, '49.262062,-123.104656': 48, '49.27033,-123.10275': 50, '49.258902,-123.109596': 29, '49.282224,-123.132778': 40, '49.265071,-123.123864': 50, '49.265198,-123.131043': 39, '49.273691,-123.102232': 36, '49.2685027,-123.0975014': 38, '49.278529,-123.100017': 44, '49.288682,-123.11818': 50, '49.258864,-123.14353': 18, '49.271741,-123.155421': 40, '49.262822,-123.14338': 46, '49.263635,-123.099236': 42, '49.28763,-123.127245': 50, '49.297933,-123.130758': 2, '49.258819,-123.131317': 6, '49.280284,-123.097052': 48, '49.276294,-123.106534': 43, '49.277469,-123.081315': 19, '49.277665,-123.073653': 50, '49.277436,-123.070427': 41, '49.280332,-123.070068': 44, '49.279369,-123.091241': 25, '49.283992,-123.091206': 23, '49.274881,-123.069323': 50, '49.275882,-123.071865': 50, '49.273777,-123.092723': 13, '49.265005,-123.079481': 5, '49.265024,-123.08127': 4, '49.271377,-123.069416': 48, '49.268616,-123.069908': 50, '49.266969,-123.069936': 50, '49.263242,-123.070521': 49, '49.261403,-123.070102': 37, '49.261263,-123.073707': 35, '49.262242,-123.081459': 5, '49.262321,-123.09306': 29, '49.264251,-123.073853': 41, '49.266751,-123.073501': 50, '49.270684,-123.073562': 49, '49.2731,-123.0732': 50, '49.254667,-123.101389': 42, '49.256694,-123.096579': 35, '49.258352,-123.096337': 35, '49.258817,-123.092797': 34, '49.26151,-123.089413': 24, '49.263382,-123.088837': 21, '49.261353,-123.085333': 17, '49.264466,-123.085183': 18, '49.280197,-123.065859': 27, '49.266725,-123.065925': 47, '49.261188,-123.066009': 35, '49.256857,-123.065646': 19, '49.283986,-123.065264': 37, '49.257985,-123.083366': 10, '49.257939,-123.089531': 25, '49.256496,-123.075426': 2, '49.283236,-123.070443': 30, '49.267266,-123.090786': 11, '49.265242,-123.095577': 47, '49.265213,-123.090785': 19, '49.302577,-123.155616': 2, '49.277595,-123.09583': 50, '49.279235,-123.087528': 16, '49.277333,-123.087359': 13, '49.273103,-123.069892': 50, '49.261973,-123.09725': 50, '49.275295,-123.132585': 40, '49.285871,-123.12105': 50, '49.284893,-123.128685': 45, '49.263962,-123.112621': 50, '49.277615,-123.091654': 16, '49.282214,-123.114101': 50, '49.266456,-123.100324': 50, '49.268216,-123.103168': 50, '49.284554,-123.111031': 50, '49.280216,-123.117639': 50, '49.266314,-123.116011': 50, '49.280852,-123.084746': 13, '49.285512,-123.1384': 49, '49.27821,-123.136972': 40, '49.281301,-123.139108': 37, '49.283298,-123.142288': 35, '49.280787,-123.115271': 50, '49.266476,-123.109389': 50, '49.290587,-123.13625': 50, '49.312568,-123.144177': 3, '49.262835,-123.152626': 19, '49.256825,-123.105234': 39, '49.275683,-123.124388': 50, '49.263518,-123.09568': 50, '49.28691,-123.128818': 48, '49.282503,-123.124697': 50, '49.283749,-123.136133': 35, '49.262944,-123.148109': 32, '49.27029,-123.135025': 50, '49.280427,-123.074082': 27, '49.279259,-123.119145': 50, '49.285836,-123.127265': 50, '49.272969,-123.164325': 0, '49.27247,-123.185643': 15, '49.271471,-123.17731': 4, '49.290112,-123.127062': 46, '49.263523,-123.155267': 26, '49.264928,-123.168068': 44, '49.264483,-123.173926': 50, '49.264579,-123.18373': 44, '49.263746,-123.069892': 50, '49.258761,-123.127071': 11, '49.268974,-123.190701': 13, '49.273011,-123.159663': 18, '49.266924,-123.173849': 50, '49.264326,-123.164725': 32, '49.266636,-123.183661': 40, '49.254818,-123.114785': 40, '49.268837,-123.177633': 17, '49.255034,-123.120226': 30, '49.271044,-123.170661': 15, '49.252691,-123.101289': 37, '49.272172,-123.097978': 37, '49.271082,-123.191458': 4, '49.27808,-123.130557': 50, '49.269969,-123.109623': 34, '49.287528,-123.142139': 44, '49.28803,-123.142135': 48, '49.259579,-123.114769': 43, '49.2890705989865,-123.138407369468': 50, '49.287782,-123.12395': 50, '49.28512,-123.11242': 50, '49.247854,-123.153422': 3, '49.265939,-123.1129': 49, '49.261122,-123.097571': 50, '49.267725,-123.11311': 36, '49.245135,-123.116098': 2, '49.274232,-123.129998': 50, '49.238105,-123.154966': 43, '49.246243,-123.124373': 9, '49.249722,-123.104991': 46, '49.243375,-123.104978': 29, '49.282087,-123.056909': 42, '49.283968,-123.061615': 44, '49.287464,-123.060771': 15, '49.285575,-123.061575': 23, '49.251358,-123.115637': 27, '49.249184,-123.116141': 5, '49.245535,-123.120496': 6, '49.289255,-123.132677': 50, '49.252656,-123.067965': 10, '49.277527,-123.129464': 50, '49.259469,-123.145718': 17}

In [105]:
fsq_url = "https://api.foursquare.com/v3/places/search"
fsq_headers = {
    'Accept': "application/json",
    "Authorization": fsq_api_key
}

fsq_park_df = pd.DataFrame()
fsq_park_dict= {}

for i in locations:
    fsq_params = {
        "categories": '16032', #bars 13003, cafes 13032, tattoo shop 11075, restaurant 13065, parks 16032
        "ll": i,
        "radius": '500',
        "limit":'50'
    }

    response = requests.request("GET",fsq_url, params=fsq_params,headers=fsq_headers)
    data = response.json()
    fsq_park_dict[i] = len(data['results'])
    
    fsq_df = pd.json_normalize(data = data['results'])
    fsq_park_df = pd.concat([fsq_park_df, fsq_df])

print(fsq_park_dict)      
# fsq_cafe_df

{'49.262487,-123.114397': 0, '49.274566,-123.121817': 8, '49.279764,-123.110154': 2, '49.260599,-123.113504': 1, '49.264215,-123.117772': 1, '49.270877,-123.115103': 6, '49.26893,-123.11813': 2, '49.271721,-123.104207': 10, '49.287214,-123.11287': 2, '49.282409,-123.118541': 5, '49.287097,-123.118551': 8, '49.273471,-123.118016': 6, '49.282758,-123.122092': 6, '49.286042,-123.113176': 4, '49.28602,-123.116624': 6, '49.279739,-123.116251': 1, '49.277483,-123.114279': 4, '49.275679,-123.116963': 4, '49.282759,-123.106955': 3, '49.288444,-123.139203': 2, '49.289124,-123.12196': 6, '49.28062,-123.12482': 5, '49.279938,-123.127478': 6, '49.273663,-123.127075': 6, '49.28972,-123.144028': 5, '49.285253,-123.134356': 7, '49.283343,-123.131099': 7, '49.284605,-123.108662': 2, '49.279821,-123.10802': 4, '49.278004,-123.105664': 4, '49.279342,-123.101822': 4, '49.273833,-123.114373': 7, '49.28526,-123.141809': 2, '49.281506,-123.120101': 5, '49.276115,-123.114496': 4, '49.272827,-123.147744': 5, '49.269361,-123.13782': 9, '49.2653,-123.13811': 8, '49.262598,-123.138921': 5, '49.25894,-123.139272': 2, '49.258763,-123.115392': 1, '49.266724,-123.104824': 4, '49.262141,-123.101961': 5, '49.268269,-123.147885': 5, '49.275717,-123.142564': 10, '49.276436,-123.11877': 6, '49.277844,-123.120942': 6, '49.265089,-123.119425': 3, '49.28026,-123.135244': 11, '49.291909,-123.140713': 7, '49.293257,-123.138563': 5, '49.288011,-123.132006': 3, '49.28117,-123.104419': 6, '49.283227,-123.120523': 5, '49.299292,-123.130281': 4, '49.29534,-123.150433': 7, '49.294318,-123.148808': 11, '49.298657,-123.121176': 0, '49.259183,-123.120126': 1, '49.263837,-123.105173': 3, '49.270721,-123.146175': 4, '49.265605,-123.152566': 5, '49.267222,-123.153157': 2, '49.262255,-123.126217': 4, '49.257654,-123.153212': 2, '49.25919,-123.148268': 2, '49.25741,-123.148531': 1, '49.285953,-123.124066': 8, '49.280881,-123.130672': 4, '49.256845,-123.120071': 4, '49.25849,-123.104799': 6, '49.258425,-123.100792': 4, '49.270905,-123.126006': 8, '49.273568,-123.129935': 6, '49.277141,-123.122589': 5, '49.267859,-123.145782': 4, '49.265336,-123.145823': 6, '49.267628,-123.127698': 7, '49.275938,-123.145939': 7, '49.2756,-123.102661': 8, '49.284157,-123.099917': 4, '49.258924,-123.152591': 4, '49.266774,-123.141135': 7, '49.273355,-123.154493': 1, '49.276144,-123.151272': 3, '49.268339,-123.157443': 1, '49.284062,-123.095097': 4, '49.261742,-123.13148': 3, '49.262206,-123.109091': 3, '49.27023,-123.10651': 7, '49.262062,-123.104656': 3, '49.27033,-123.10275': 6, '49.258902,-123.109596': 3, '49.282224,-123.132778': 8, '49.265071,-123.123864': 6, '49.265198,-123.131043': 7, '49.273691,-123.102232': 7, '49.2685027,-123.0975014': 1, '49.278529,-123.100017': 4, '49.288682,-123.11818': 6, '49.258864,-123.14353': 2, '49.271741,-123.155421': 1, '49.262822,-123.14338': 5, '49.263635,-123.099236': 3, '49.28763,-123.127245': 6, '49.297933,-123.130758': 4, '49.258819,-123.131317': 0, '49.280284,-123.097052': 4, '49.276294,-123.106534': 6, '49.277469,-123.081315': 2, '49.277665,-123.073653': 3, '49.277436,-123.070427': 4, '49.280332,-123.070068': 2, '49.279369,-123.091241': 1, '49.283992,-123.091206': 2, '49.274881,-123.069323': 4, '49.275882,-123.071865': 4, '49.273777,-123.092723': 1, '49.265005,-123.079481': 3, '49.265024,-123.08127': 3, '49.271377,-123.069416': 4, '49.268616,-123.069908': 4, '49.266969,-123.069936': 5, '49.263242,-123.070521': 2, '49.261403,-123.070102': 2, '49.261263,-123.073707': 5, '49.262242,-123.081459': 3, '49.262321,-123.09306': 4, '49.264251,-123.073853': 4, '49.266751,-123.073501': 3, '49.270684,-123.073562': 4, '49.2731,-123.0732': 3, '49.254667,-123.101389': 6, '49.256694,-123.096579': 3, '49.258352,-123.096337': 2, '49.258817,-123.092797': 3, '49.26151,-123.089413': 3, '49.263382,-123.088837': 2, '49.261353,-123.085333': 4, '49.264466,-123.085183': 3, '49.280197,-123.065859': 1, '49.266725,-123.065925': 3, '49.261188,-123.066009': 1, '49.256857,-123.065646': 4, '49.283986,-123.065264': 0, '49.257985,-123.083366': 2, '49.257939,-123.089531': 2, '49.256496,-123.075426': 4, '49.283236,-123.070443': 0, '49.267266,-123.090786': 2, '49.265242,-123.095577': 3, '49.265213,-123.090785': 4, '49.302577,-123.155616': 0, '49.277595,-123.09583': 0, '49.279235,-123.087528': 2, '49.277333,-123.087359': 2, '49.273103,-123.069892': 3, '49.261973,-123.09725': 3, '49.275295,-123.132585': 7, '49.285871,-123.12105': 8, '49.284893,-123.128685': 5, '49.263962,-123.112621': 2, '49.277615,-123.091654': 0, '49.282214,-123.114101': 2, '49.266456,-123.100324': 5, '49.268216,-123.103168': 2, '49.284554,-123.111031': 2, '49.280216,-123.117639': 3, '49.266314,-123.116011': 1, '49.280852,-123.084746': 1, '49.285512,-123.1384': 3, '49.27821,-123.136972': 13, '49.281301,-123.139108': 6, '49.283298,-123.142288': 3, '49.280787,-123.115271': 1, '49.266476,-123.109389': 3, '49.290587,-123.13625': 6, '49.312568,-123.144177': 1, '49.262835,-123.152626': 6, '49.256825,-123.105234': 5, '49.275683,-123.124388': 6, '49.263518,-123.09568': 4, '49.28691,-123.128818': 4, '49.282503,-123.124697': 7, '49.283749,-123.136133': 7, '49.262944,-123.148109': 4, '49.27029,-123.135025': 8, '49.280427,-123.074082': 1, '49.279259,-123.119145': 5, '49.285836,-123.127265': 7, '49.272969,-123.164325': 7, '49.27247,-123.185643': 2, '49.271471,-123.17731': 3, '49.290112,-123.127062': 6, '49.263523,-123.155267': 5, '49.264928,-123.168068': 1, '49.264483,-123.173926': 1, '49.264579,-123.18373': 1, '49.263746,-123.069892': 4, '49.258761,-123.127071': 2, '49.268974,-123.190701': 0, '49.273011,-123.159663': 3, '49.266924,-123.173849': 3, '49.264326,-123.164725': 2, '49.266636,-123.183661': 1, '49.254818,-123.114785': 4, '49.268837,-123.177633': 3, '49.255034,-123.120226': 4, '49.271044,-123.170661': 6, '49.252691,-123.101289': 4, '49.272172,-123.097978': 5, '49.271082,-123.191458': 1, '49.27808,-123.130557': 8, '49.269969,-123.109623': 5, '49.287528,-123.142139': 5, '49.28803,-123.142135': 6, '49.259579,-123.114769': 1, '49.2890705989865,-123.138407369468': 4, '49.287782,-123.12395': 7, '49.28512,-123.11242': 3, '49.247854,-123.153422': 2, '49.265939,-123.1129': 1, '49.261122,-123.097571': 3, '49.267725,-123.11311': 3, '49.245135,-123.116098': 3, '49.274232,-123.129998': 7, '49.238105,-123.154966': 2, '49.246243,-123.124373': 1, '49.249722,-123.104991': 1, '49.243375,-123.104978': 6, '49.282087,-123.056909': 2, '49.283968,-123.061615': 2, '49.287464,-123.060771': 2, '49.285575,-123.061575': 3, '49.251358,-123.115637': 4, '49.249184,-123.116141': 2, '49.245535,-123.120496': 2, '49.289255,-123.132677': 7, '49.252656,-123.067965': 3, '49.277527,-123.129464': 7, '49.259469,-123.145718': 2}

In [97]:
tattoo_rad_df = pd.Series(fsq_tattoo_dict).to_frame().reset_index()
tattoo_rad_df.columns = ["lat_long","tattoo_500m_rad"]
tattoo_rad_df#.sort_values(0,ascending= False).head(130)

                  lat_long  tattoo_500m_rad
0    49.262487,-123.114397                3
1    49.274566,-123.121817                6
2    49.279764,-123.110154                5
3    49.260599,-123.113504                2
4    49.264215,-123.117772                0
..                     ...              ...
236  49.245535,-123.120496                0
237  49.289255,-123.132677                0
238  49.252656,-123.067965                0
239  49.277527,-123.129464                5
240  49.259469,-123.145718                0

[241 rows x 2 columns]

In [93]:
bar_rad_df = pd.Series(fsq_bar_dict).to_frame().reset_index()
bar_rad_df.columns = ["lat_long","bars_500m_rad"]
bar_rad_df#.sort_values(0,ascending= False).head(130)

                  lat_long  bars_500m_rad
0    49.262487,-123.114397              5
1    49.274566,-123.121817             50
2    49.279764,-123.110154             40
3    49.260599,-123.113504              4
4    49.264215,-123.117772              7
..                     ...            ...
236  49.245535,-123.120496              0
237  49.289255,-123.132677              8
238  49.252656,-123.067965              0
239  49.277527,-123.129464             33
240  49.259469,-123.145718              2

[241 rows x 2 columns]

In [94]:
cafe_rad_df = pd.Series(fsq_cafe_dict).to_frame().reset_index()
cafe_rad_df.columns = ["lat_long","cafes_500m_rad"]
cafe_rad_df#.sort_values(0,ascending= False).head(130)

                  lat_long  cafes_500m_rad
0    49.262487,-123.114397              25
1    49.274566,-123.121817              24
2    49.279764,-123.110154              50
3    49.260599,-123.113504              18
4    49.264215,-123.117772              26
..                     ...             ...
236  49.245535,-123.120496               5
237  49.289255,-123.132677              31
238  49.252656,-123.067965               3
239  49.277527,-123.129464              33
240  49.259469,-123.145718               3

[241 rows x 2 columns]

In [95]:
rest_rad_df = pd.Series(fsq_rest_dict).to_frame().reset_index()
rest_rad_df.columns = ["lat_long","restaurants_500m_rad"]
rest_rad_df#.sort_values(0,ascending= False).head(130)

                  lat_long  restaurants_500m_rad
0    49.262487,-123.114397                    47
1    49.274566,-123.121817                    50
2    49.279764,-123.110154                    50
3    49.260599,-123.113504                    48
4    49.264215,-123.117772                    50
..                     ...                   ...
236  49.245535,-123.120496                     6
237  49.289255,-123.132677                    50
238  49.252656,-123.067965                    10
239  49.277527,-123.129464                    50
240  49.259469,-123.145718                    17

[241 rows x 2 columns]

In [107]:
park_rad_df = pd.Series(fsq_park_dict).to_frame().reset_index()
park_rad_df.columns = ["lat_long","parks_500m_rad"]
park_rad_df#.sort_values(0,ascending= False).head(130)

                  lat_long  parks_500m_rad
0    49.262487,-123.114397               0
1    49.274566,-123.121817               8
2    49.279764,-123.110154               2
3    49.260599,-123.113504               1
4    49.264215,-123.117772               1
..                     ...             ...
236  49.245535,-123.120496               2
237  49.289255,-123.132677               7
238  49.252656,-123.067965               3
239  49.277527,-123.129464               7
240  49.259469,-123.145718               2

[241 rows x 2 columns]

Put your parsed results into a DataFrame

In [109]:
df1 = pd.merge(tattoo_rad_df, bar_rad_df, on="lat_long")
df2 = pd.merge(df1, cafe_rad_df, on="lat_long")
df3 = pd.merge(df2, rest_rad_df, on="lat_long")
van_rad_data_df = pd.merge(df3, park_rad_df, on="lat_long")
van_rad_data_df

,lat_long,tattoo_500m_rad,bars_500m_rad,cafes_500m_rad,restaurants_500m_rad,parks_500m_rad
0,"49.262487,-123.114397",3,5,25,47,0
1,"49.274566,-123.121817",6,50,24,50,8
2,"49.279764,-123.110154",5,40,50,50,2
3,"49.260599,-123.113504",2,4,18,48,1
4,"49.264215,-123.117772",0,7,26,50,1
...,...,...,...,...,...,...
236,"49.245535,-123.120496",0,0,5,6,2
237,"49.289255,-123.132677",0,8,31,50,7
238,"49.252656,-123.067965",0,0,3,10,3
239,"49.277527,-123.129464",5,33,33,50,7
240,"49.259469,-123.145718",0,2,3,17,2

In [110]:
van_rad_data_df.to_csv('../data/van_rad_data_df.csv', index=False)

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [4]:
yelp_api_key = os.environ['YELP_API']

In [114]:
# yelp_url = "https://api.yelp.com/v3/businesses/search"
# yelp_headers = {
#     'Accept': "application/json",
#     "Authorization": "Bearer " + yelp_api_key
# }

# yelp_params = {
#     "latitude": "49.262487",
#     "longitude": "-123.114397",
#     "categories":'bar',
#     "radius":'500'
# }

# response = requests.request("GET",yelp_url, params=yelp_params,headers=yelp_headers)
# data = response.json()

# yelp_df = pd.json_normalize(data = data['businesses'])
# yelp_df


yelp_bar_df = pd.DataFrame()
yelp_bar_dict= {}

for i,j in zip(lat,long):
    fsq_params = {
        "latitude": i,
        "longitude": j,
        "categories":'bar',
        "radius":'200'
    }

    response = requests.request("GET",yelp_url, params=yelp_params,headers=yelp_headers)
    data = response.json()
    yelp_bar_dict[i,j] = len(data['businesses'])
    
    yelp_df = pd.json_normalize(data = data['businesses'])
    yelp_bar_df = pd.concat([yelp_bar_df, yelp_df])

print(yelp_bar_dict)      
yelp_bar_df

{(49.262487, -123.114397): 20, (49.274566, -123.121817): 20, (49.279764, -123.110154): 20, (49.260599, -123.113504): 20, (49.264215, -123.117772): 20, (49.270877, -123.115103): 20, (49.26893, -123.11813): 20, (49.271721, -123.104207): 20, (49.287214, -123.11287): 20, (49.282409, -123.118541): 20, (49.287097, -123.118551): 20, (49.273471, -123.118016): 20, (49.282758, -123.122092): 20, (49.286042, -123.113176): 20, (49.28602, -123.116624): 20, (49.279739, -123.116251): 20, (49.277483, -123.114279): 20, (49.275679, -123.116963): 20, (49.282759, -123.106955): 20, (49.288444, -123.139203): 20, (49.289124, -123.12196): 20, (49.28062, -123.12482): 20, (49.279938, -123.127478): 20, (49.273663, -123.127075): 20, (49.28972, -123.144028): 20, (49.285253, -123.134356): 20, (49.283343, -123.131099): 20, (49.284605, -123.108662): 20, (49.279821, -123.10802): 20, (49.278004, -123.105664): 20, (49.279342, -123.101822): 20, (49.273833, -123.114373): 20, (49.28526, -123.141809): 20, (49.281506, -123.120101): 20, (49.276115, -123.114496): 20, (49.272827, -123.147744): 20, (49.269361, -123.13782): 20, (49.2653, -123.13811): 20, (49.262598, -123.138921): 20, (49.25894, -123.139272): 20, (49.258763, -123.115392): 20, (49.266724, -123.104824): 20, (49.262141, -123.101961): 20, (49.268269, -123.147885): 20, (49.275717, -123.142564): 20, (49.276436, -123.11877): 20, (49.277844, -123.120942): 20, (49.265089, -123.119425): 20, (49.28026, -123.135244): 20, (49.291909, -123.140713): 20, (49.293257, -123.138563): 20, (49.288011, -123.132006): 20, (49.28117, -123.104419): 20, (49.283227, -123.120523): 20, (49.299292, -123.130281): 20, (49.29534, -123.150433): 20, (49.294318, -123.148808): 20, (49.298657, -123.121176): 20, (49.259183, -123.120126): 20, (49.263837, -123.105173): 20, (49.270721, -123.146175): 20, (49.265605, -123.152566): 20, (49.267222, -123.153157): 20, (49.262255, -123.126217): 20, (49.257654, -123.153212): 20, (49.25919, -123.148268): 20, (49.25741, -123.148531): 20, (49.285953, -123.124066): 20, (49.280881, -123.130672): 20, (49.256845, -123.120071): 20, (49.25849, -123.104799): 20, (49.258425, -123.100792): 20, (49.270905, -123.126006): 20, (49.273568, -123.129935): 20, (49.277141, -123.122589): 20, (49.267859, -123.145782): 20, (49.265336, -123.145823): 20, (49.267628, -123.127698): 20, (49.275938, -123.145939): 20, (49.2756, -123.102661): 20, (49.284157, -123.099917): 20, (49.258924, -123.152591): 20, (49.266774, -123.141135): 20, (49.273355, -123.154493): 20, (49.276144, -123.151272): 20, (49.268339, -123.157443): 20, (49.284062, -123.095097): 20, (49.261742, -123.13148): 20, (49.262206, -123.109091): 20, (49.27023, -123.10651): 20, (49.262062, -123.104656): 20, (49.27033, -123.10275): 20, (49.258902, -123.109596): 20, (49.282224, -123.132778): 20, (49.265071, -123.123864): 20, (49.265198, -123.131043): 20, (49.273691, -123.102232): 20, (49.2685027, -123.0975014): 20, (49.278529, -123.100017): 20, (49.288682, -123.11818): 20, (49.258864, -123.14353): 20, (49.271741, -123.155421): 20, (49.262822, -123.14338): 20, (49.263635, -123.099236): 20, (49.28763, -123.127245): 20, (49.297933, -123.130758): 20, (49.258819, -123.131317): 20, (49.280284, -123.097052): 20, (49.276294, -123.106534): 20, (49.277469, -123.081315): 20, (49.277665, -123.073653): 20, (49.277436, -123.070427): 20, (49.280332, -123.070068): 20, (49.279369, -123.091241): 20, (49.283992, -123.091206): 20, (49.274881, -123.069323): 20, (49.275882, -123.071865): 20, (49.273777, -123.092723): 20, (49.265005, -123.079481): 20, (49.265024, -123.08127): 20, (49.271377, -123.069416): 20, (49.268616, -123.069908): 20, (49.266969, -123.069936): 20, (49.263242, -123.070521): 20, (49.261403, -123.070102): 20, (49.261263, -123.073707): 20, (49.262242, -123.081459): 20, (49.262321, -123.09306): 20, (49.264251, -123.073853): 20, (49.266751, -123.073501): 20, (49.270684, -123.073562): 20, (49.2731, -123.0732): 20, (49.254667, -123.101389): 20, (49.256694, -123.096579): 20, (49.258352, -123.096337): 20, (49.258817, -123.092797): 20, (49.26151, -123.089413): 20, (49.263382, -123.088837): 20, (49.261353, -123.085333): 20, (49.264466, -123.085183): 20, (49.280197, -123.065859): 20, (49.266725, -123.065925): 20, (49.261188, -123.066009): 20, (49.256857, -123.065646): 20, (49.283986, -123.065264): 20, (49.257985, -123.083366): 20, (49.257939, -123.089531): 20, (49.256496, -123.075426): 20, (49.283236, -123.070443): 20, (49.267266, -123.090786): 20, (49.265242, -123.095577): 20, (49.265213, -123.090785): 20, (49.302577, -123.155616): 20, (49.277595, -123.09583): 20, (49.279235, -123.087528): 20, (49.277333, -123.087359): 20, (49.273103, -123.069892): 20, (49.261973, -123.09725): 20, (49.275295, -123.132585): 20, (49.285871, -123.12105): 20, (49.284893, -123.128685): 20, (49.263962, -123.112621): 20, (49.277615, -123.091654): 20, (49.282214, -123.114101): 20, (49.266456, -123.100324): 20, (49.268216, -123.103168): 20, (49.284554, -123.111031): 20, (49.280216, -123.117639): 20, (49.266314, -123.116011): 20, (49.280852, -123.084746): 20, (49.285512, -123.1384): 20, (49.27821, -123.136972): 20, (49.281301, -123.139108): 20, (49.283298, -123.142288): 20, (49.280787, -123.115271): 20, (49.266476, -123.109389): 20, (49.290587, -123.13625): 20, (49.312568, -123.144177): 20, (49.262835, -123.152626): 20, (49.256825, -123.105234): 20, (49.275683, -123.124388): 20, (49.263518, -123.09568): 20, (49.28691, -123.128818): 20, (49.282503, -123.124697): 20, (49.283749, -123.136133): 20, (49.262944, -123.148109): 20, (49.27029, -123.135025): 20, (49.280427, -123.074082): 20, (49.279259, -123.119145): 20, (49.285836, -123.127265): 20, (49.272969, -123.164325): 20, (49.27247, -123.185643): 20, (49.271471, -123.17731): 20, (49.290112, -123.127062): 20, (49.263523, -123.155267): 20, (49.264928, -123.168068): 20, (49.264483, -123.173926): 20, (49.264579, -123.18373): 20, (49.263746, -123.069892): 20, (49.258761, -123.127071): 20, (49.268974, -123.190701): 20, (49.273011, -123.159663): 20, (49.266924, -123.173849): 20, (49.264326, -123.164725): 20, (49.266636, -123.183661): 20, (49.254818, -123.114785): 20, (49.268837, -123.177633): 20, (49.255034, -123.120226): 20, (49.271044, -123.170661): 20, (49.252691, -123.101289): 20, (49.272172, -123.097978): 20, (49.271082, -123.191458): 20, (49.27808, -123.130557): 20, (49.269969, -123.109623): 20, (49.287528, -123.142139): 20, (49.28803, -123.142135): 20, (49.259579, -123.114769): 20, (49.2890705989865, -123.138407369468): 20, (49.287782, -123.12395): 20, (49.28512, -123.11242): 20, (49.247854, -123.153422): 20, (49.265939, -123.1129): 20, (49.261122, -123.097571): 20, (49.267725, -123.11311): 20, (49.245135, -123.116098): 20, (49.274232, -123.129998): 20, (49.238105, -123.154966): 20, (49.246243, -123.124373): 20, (49.249722, -123.104991): 20, (49.243375, -123.104978): 20, (49.282087, -123.056909): 20, (49.283968, -123.061615): 20, (49.287464, -123.060771): 20, (49.285575, -123.061575): 20, (49.251358, -123.115637): 20, (49.249184, -123.116141): 20, (49.245535, -123.120496): 20, (49.289255, -123.132677): 20, (49.252656, -123.067965): 20, (49.277527, -123.129464): 20, (49.259469, -123.145718): 20}

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,transactions,...,coordinates.latitude,coordinates.longitude,location.address1,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address
0,6iOAgzJ0DRZNSKA3FSrrOg,la-taqueria-pinche-taco-shop-vancouver,La Taqueria Pinche Taco Shop,https://s3-media1.fl.yelpcdn.com/bphoto/fjhIj3...,False,https://www.yelp.com/biz/la-taqueria-pinche-ta...,679,"[{'alias': 'mexican', 'title': 'Mexican'}]",4.0,[],...,49.263559,-123.112736,2450 Yukon Street,,,Vancouver,V5Z 3V6,CA,BC,"[2450 Yukon Street, Vancouver, BC V5Z 3V6, Can..."
1,NensKn1MSVU_rm-1Y6WlFA,marulilu-cafe-vancouver,Marulilu Cafe,https://s3-media2.fl.yelpcdn.com/bphoto/uwwarf...,False,https://www.yelp.com/biz/marulilu-cafe-vancouv...,283,"[{'alias': 'cafes', 'title': 'Cafes'}]",4.0,[],...,49.263380,-123.114150,451 W Broadway,,,Vancouver,V5Y 1R4,CA,BC,"[451 W Broadway, Vancouver, BC V5Y 1R4, Canada]"
2,AEOyRbQtYD3bmX1qJWvt4g,peaceful-restaurant-vancouver,Peaceful Restaurant,https://s3-media2.fl.yelpcdn.com/bphoto/Otuhde...,False,https://www.yelp.com/biz/peaceful-restaurant-v...,619,"[{'alias': 'chinese', 'title': 'Chinese'}, {'a...",3.5,[],...,49.263147,-123.116143,110-532 W Broadway,,,Vancouver,V5Z 1E9,CA,BC,"[110-532 W Broadway, Vancouver, BC V5Z 1E9, Ca..."
3,XAH2HpuUUtu7CUO26pbs4w,saku-vancouver-8,Saku,https://s3-media1.fl.yelpcdn.com/bphoto/mKOSej...,False,https://www.yelp.com/biz/saku-vancouver-8?adju...,197,"[{'alias': 'japanese', 'title': 'Japanese'}]",4.0,[],...,49.263125,-123.116603,548 W Broadway,,None,Vancouver,V5Z 1E9,CA,BC,"[548 W Broadway, Vancouver, BC V5Z 1E9, Canada]"
4,nkDZY5xqihF3XtZMzzfqqg,hokkaido-ramen-santouka-vancouver-5,Hokkaido Ramen Santouka,https://s3-media2.fl.yelpcdn.com/bphoto/9Fe-Lq...,False,https://www.yelp.com/biz/hokkaido-ramen-santou...,220,"[{'alias': 'noodles', 'title': 'Noodles'}, {'a...",4.0,[],...,49.263127,-123.116892,558 W Broadway,,None,Vancouver,V5Z 1E9,CA,BC,"[558 W Broadway, Vancouver, BC V5Z 1E9, Canada]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,uZOaRCd8SO5FudDmqcqq1A,mr-japanese-curry-vancouver,Mr Japanese Curry,https://s3-media3.fl.yelpcdn.com/bphoto/apREzf...,False,https://www.yelp.com/biz/mr-japanese-curry-van...,34,"[{'alias': 'japanese', 'title': 'Japanese'}]",4.0,[],...,49.263802,-123.113700,446 West 8th Avenue,None,,Vancouver,V5Y 1N9,CA,BC,"[446 West 8th Avenue, Vancouver, BC V5Y 1N9, C..."
16,MQK-AA9xOFFLKBfd7bVSZw,red-truck-beer-vancouver,Red Truck Beer,https://s3-media1.fl.yelpcdn.com/bphoto/sgzC6b...,False,https://www.yelp.com/biz/red-truck-beer-vancou...,84,"[{'alias': 'breweries', 'title': 'Breweries'},...",4.0,[],...,49.268784,-123.096585,295 E 1st Avenue,,,Vancouver,V5T 1A7,CA,BC,"[295 E 1st Avenue, Vancouver, BC V5T 1A7, Canada]"
17,1AA4EjIIXywxOSnbyZ9vLA,pho-extreme-xe-lua-vancouver,Pho Extreme Xe Lua,https://s3-media4.fl.yelpcdn.com/bphoto/5h2JTc...,False,https://www.yelp.com/biz/pho-extreme-xe-lua-va...,101,"[{'alias': 'vietnamese', 'title': 'Vietnamese'...",2.5,[],...,49.263357,-123.114155,457 W Broadway,,,Vancouver,V5Y 4A8,CA,BC,"[457 W Broadway, Vancouver, BC V5Y 4A8, Canada]"
18,vGyDxnk9P975Rwrs05cdVw,city-of-vancouver-vancouver-9,City of Vancouver,https://s3-media3.fl.yelpcdn.com/bphoto/9guG0C...,False,https://www.yelp.com/biz/city-of-vancouver-van...,10,"[{'alias': 'localflavor', 'title': 'Local Flav...",4.5,[],...,49.260884,-123.113927,453 West 12th Avenue,,None,Vancouver,V5Y 1V4,CA,BC,"[453 West 12th Avenue, Vancouver, BC V5Y 1V4, ..."
19,rRb2CvNCNWyPSQdeVme9-Q,takenaka-vancouver,Takenaka,https://s3-media2.fl.yelpcdn.com/bphoto/inXchp...,False,https://www.yelp.com/biz/takenaka-vancouver?ad...,39,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.5,[],...,49.278309,-123.075580,1370 Georgia Street,,None,Vancouver,V5L 2A8,CA,BC,"[1370 Georgia Street, Vancouver, BC V5L 2A8, C..."

In [113]:
yelp_bars_nearby_df = pd.Series(yelp_bar_dict).to_frame().reset_index()
yelp_bars_nearby_df.columns = ["Lat", "Long","bars_within_500m_radius"]
yelp_bars_nearby_df#.sort_values(0,ascending= False).head(130)

           Lat        Long  bars_within_500m_radius
0    49.262487 -123.114397                       20
1    49.274566 -123.121817                       20
2    49.279764 -123.110154                       20
3    49.260599 -123.113504                       20
4    49.264215 -123.117772                       20
..         ...         ...                      ...
236  49.245535 -123.120496                       20
237  49.289255 -123.132677                       20
238  49.252656 -123.067965                       20
239  49.277527 -123.129464                       20
240  49.259469 -123.145718                       20

[241 rows x 3 columns]

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

the Yelp business API had a limit of 20 business per query and 20 business within a 500 meter radius of each bike station.   Given the approach I was taking to my analysis, there is no potential relationship to be drawn between businesses within a 500 meter radius and the total bikes per bike station.  Therefore I will use foursquare results for my statistical model and regression analysis.

Foursquare provides a wider array of categories of data, but Yelp has more information about local restaurants than Foursquare.

Get the top 10 restaurants according to their rating

In [120]:
yelp_url = "https://api.yelp.com/v3/businesses/search"
yelp_headers = {
    'Accept': "application/json",
    "Authorization": "Bearer " + yelp_api_key
}

yelp_params = {
    "latitude": '49.262487',
    "longitude": '-123.114397',
    "categories":'bar',
    "radius":'5000',
    "limit":'10',
    "sort_by":'rating'
}

response = requests.request("GET",yelp_url, params=yelp_params,headers=yelp_headers)
data = response.json()

yelp_top10_df = pd.json_normalize(data = data['businesses'])
yelp_top10_df

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,transactions,...,coordinates.latitude,coordinates.longitude,location.address1,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address
0,64drFDGorfQPecRLP-lThw,obanhmi-vancouver-2,Obanhmi,https://s3-media2.fl.yelpcdn.com/bphoto/NpX5S4...,False,https://www.yelp.com/biz/obanhmi-vancouver-2?a...,6,"[{'alias': 'vietnamese', 'title': 'Vietnamese'...",5.0,[],...,49.263646,-123.142283,102-1668 W Broadway,,None,Vancouver,V6J 1X6,CA,BC,"[102-1668 W Broadway, Vancouver, BC V6J 1X6, C..."
1,_IBfaGM3WOVtZ-ANkEPmJw,sushi-master-vancouver-3,Sushi Master,https://s3-media2.fl.yelpcdn.com/bphoto/t8Qo3a...,False,https://www.yelp.com/biz/sushi-master-vancouve...,5,"[{'alias': 'sushi', 'title': 'Sushi Bars'}]",5.0,[],...,49.263747,-123.139320,1509 W Broadway,None,,Vancouver,V6H 3G5,CA,BC,"[1509 W Broadway, Vancouver, BC V6H 3G5, Canada]"
2,6qrRd4bXgVcJjXQEnpfi-Q,vv-tapas-lounge-vancouver,VV Tapas Lounge,https://s3-media2.fl.yelpcdn.com/bphoto/DfrP_z...,False,https://www.yelp.com/biz/vv-tapas-lounge-vanco...,11,"[{'alias': 'tapas', 'title': 'Tapas Bars'}]",5.0,[],...,49.281163,-123.083047,957 E Hastings Street,None,,Vancouver,V6A 1R9,CA,BC,"[957 E Hastings Street, Vancouver, BC V6A 1R9,..."
3,XjczOlX_jwjBs5Jy8chhkw,that-s-it-cafe-vancouver,That’s It Cafe,https://s3-media2.fl.yelpcdn.com/bphoto/ia9X8v...,False,https://www.yelp.com/biz/that-s-it-cafe-vancou...,13,"[{'alias': 'cafes', 'title': 'Cafes'}]",5.0,[],...,49.270449,-123.141419,1612 West 1st Avenue,,None,Vancouver,V6J 3B1,CA,BC,"[1612 West 1st Avenue, Vancouver, BC V6J 3B1, ..."
4,y4vjMBAda7zdSglUnurecg,elephant-on-powell-restaurant-vancouver,Elephant On Powell Restaurant,https://s3-media2.fl.yelpcdn.com/bphoto/tc2j_t...,False,https://www.yelp.com/biz/elephant-on-powell-re...,5,"[{'alias': 'newcanadian', 'title': 'Canadian (...",5.0,[],...,49.284864,-123.066000,1879 Powell Street,,None,Vancouver,V5L 1H8,CA,BC,"[1879 Powell Street, Vancouver, BC V5L 1H8, Ca..."
5,kfqo03eeatiGz5XhWKg4qg,sushi-flamingo-vancouver,Sushi Flamingo,https://s3-media3.fl.yelpcdn.com/bphoto/nSvPGO...,False,https://www.yelp.com/biz/sushi-flamingo-vancou...,6,"[{'alias': 'sushi', 'title': 'Sushi Bars'}]",5.0,[],...,49.269313,-123.146086,1-1855 Burrad Street,,None,Vancouver,V6J 3G9,CA,BC,"[1-1855 Burrad Street, Vancouver, BC V6J 3G9, ..."
6,6vWelcDXp2E4Sna89UJ7uA,mizu-sushi-co-vancouver-2,mizu sushi co.,https://s3-media4.fl.yelpcdn.com/bphoto/87sYpu...,False,https://www.yelp.com/biz/mizu-sushi-co-vancouv...,6,"[{'alias': 'vegan', 'title': 'Vegan'}, {'alias...",5.0,[],...,49.283596,-123.073770,1507 Powell Street,Suite 150,,Vancouver,V5L 5C3,CA,BC,"[1507 Powell Street, Suite 150, Vancouver, BC ..."
7,XQrDcM6Slk65d1sjxky-lQ,grab-n-go-vancouver-2,Grab N Go,https://s3-media2.fl.yelpcdn.com/bphoto/WzU0ES...,False,https://www.yelp.com/biz/grab-n-go-vancouver-2...,5,"[{'alias': 'korean', 'title': 'Korean'}]",5.0,[],...,49.274894,-123.123011,1207 Hamilton Street,,None,Vancouver,V6B 5P6,CA,BC,"[1207 Hamilton Street, Vancouver, BC V6B 5P6, ..."
8,C1eAk88FmfZDxJBoVKzIbg,the-box-bakery-and-kitchen-pearland,The Box Bakery and Kitchen,https://s3-media3.fl.yelpcdn.com/bphoto/bxW3gl...,False,https://www.yelp.com/biz/the-box-bakery-and-ki...,46,"[{'alias': 'bakeries', 'title': 'Bakeries'}, {...",4.5,"[delivery, pickup]",...,29.542266,-95.222343,1130 Broadway St,Ste 114,,Pearland,77581,US,TX,"[1130 Broadway St, Ste 114, Pearland, TX 77581]"
9,Qw1kYX256WDxXM3zxZGsLQ,urban-tadka-vancouver-2,Urban Tadka,https://s3-media1.fl.yelpcdn.com/bphoto/BXS6cb...,False,https://www.yelp.com/biz/urban-tadka-vancouver...,9,"[{'alias': 'indpak', 'title': 'Indian'}]",5.0,[],...,49.278270,-123.075660,1370 E Georgia St,None,,Vancouver,V5L 2A8,CA,BC,"[1370 E Georgia St, Vancouver, BC V5L 2A8, Can..."

In [119]:
fsq_url = "https://api.foursquare.com/v3/places/search"
fsq_headers = {
    'Accept': "application/json",
    "Authorization": fsq_api_key
}

fsq_params = {
    "categories": '13065', #bars 13003, cafes 13032, tattoo shop 11075, restaurant 13065, parks 16032
    "ll": '49.262487,-123.114397',
    "radius": '5000',
    "limit":'10',
    "sort":'RATING'
}

response = requests.request("GET",fsq_url, params=fsq_params,headers=fsq_headers)
data = response.json()
    
fsq_top10_df = pd.json_normalize(data = data['results'])
fsq_top10_df

,fsq_id,categories,chains,distance,link,name,timezone,geocodes.main.latitude,geocodes.main.longitude,geocodes.roof.latitude,...,location.address,location.country,location.cross_street,location.formatted_address,location.locality,location.postcode,location.region,location.address_extended,related_places.parent.fsq_id,related_places.parent.name
0,4d9b41359298b1f7635b5338,"[{'id': 13034, 'name': 'Café', 'icon': {'prefi...",[],2329,/v3/places/4d9b41359298b1f7635b5338,Revolver,America/Vancouver,49.283261,-123.109473,49.283261,...,325 Cambie St,CA,btwn Hastings & Cordova,"325 Cambie St (btwn Hastings & Cordova), Vanco...",Vancouver,V6B 2N4,BC,NaN,NaN,NaN
1,51b201d27dd249ae714ba728,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",[],674,/v3/places/51b201d27dd249ae714ba728,33 Acres Brewing Co,America/Vancouver,49.263877,-123.105307,49.263877,...,15 8th Ave W,CA,btwn Manitoba & Ontario,"15 8th Ave W (btwn Manitoba & Ontario), Vancou...",Vancouver,V5Y 1M8,BC,NaN,NaN,NaN
2,55c40e66498e739ed2c87adf,"[{'id': 13065, 'name': 'Restaurant', 'icon': {...",[],2697,/v3/places/55c40e66498e739ed2c87adf,The Mackenzie Room,America/Vancouver,49.283272,-123.095032,49.283272,...,415 Powell St,CA,Powell Street,"415 Powell St (Powell Street), Vancouver BC V6...",Vancouver,V6A 1G7,BC,NaN,NaN,NaN
3,5780683c498e51523ab4851b,"[{'id': 13049, 'name': 'Diner', 'icon': {'pref...",[],3256,/v3/places/5780683c498e51523ab4851b,Raisu,America/Vancouver,49.268036,-123.158378,49.268036,...,2340 4th Ave W,CA,,"2340 4th Ave W, Vancouver BC V6K 1P1",Vancouver,V6K 1P1,BC,NaN,NaN,NaN
4,51e5b46b7dd23f304f4c023e,"[{'id': 13046, 'name': 'Ice Cream Parlor', 'ic...",[],2290,/v3/places/51e5b46b7dd23f304f4c023e,Earnest Ice Cream,America/Vancouver,49.249334,-123.089877,49.249334,...,3992 Fraser St,CA,at E 24th Ave,"3992 Fraser St (at E 24th Ave), Vancouver BC V...",Vancouver,V5V 4E4,BC,NaN,NaN,NaN
5,4d2cce46ae3a8cfa4067bf70,"[{'id': 13065, 'name': 'Restaurant', 'icon': {...",[],2348,/v3/places/4d2cce46ae3a8cfa4067bf70,Hawksworth Restaurant,America/Vancouver,49.283334,-123.119133,49.283334,...,801 Georgia St W,CA,at Howe St,"801 Georgia St W (at Howe St), Vancouver BC V6...",Vancouver,V6C 1P7,BC,# 102,4d5ec8ce29ef236ae0cb9059,Rosewood Hotel Georgia
6,4ab59f7cf964a520a97520e3,"[{'id': 13338, 'name': 'Seafood Restaurant', '...",[],2606,/v3/places/4ab59f7cf964a520a97520e3,Joe Fortes Seafood & Chop House,America/Vancouver,49.284956,-123.124545,49.284956,...,777 Thurlow St,CA,Robson St,"777 Thurlow St (Robson St), Vancouver BC V6E 3V5",Vancouver,V6E 3V5,BC,NaN,NaN,NaN
7,50d4bd11e4b0b55bb4b657a3,"[{'id': 13002, 'name': 'Bakery', 'icon': {'pre...",[],1959,/v3/places/50d4bd11e4b0b55bb4b657a3,Beaucoup Bakery & Cafe,America/Vancouver,49.266477,-123.140728,49.266477,...,2150 Fir St,CA,at W 6th Ave,"2150 Fir St (at W 6th Ave), Vancouver BC V6J 3B5",Vancouver,V6J 3B5,BC,NaN,NaN,NaN
8,5646ab13498e460c732920e8,"[{'id': 13272, 'name': 'Ramen Restaurant', 'ic...",[],2965,/v3/places/5646ab13498e460c732920e8,Ramen Danbo - Robson,America/Vancouver,49.287499,-123.128980,49.287499,...,1333 Robson St,CA,btwn Broughton & Jervis,"1333 Robson St (btwn Broughton & Jervis), Vanc...",Vancouver,V6E 1C6,BC,NaN,NaN,NaN
9,57e351fe498ea398546051b6,"[{'id': 13040, 'name': 'Dessert Shop', 'icon':...",[],1858,/v3/places/57e351fe498ea398546051b6,Nero Belgian Waffle Bar,America/Vancouver,49.278311,-123.122111,49.278311,...,1002 Seymour St,CA,Seymour and Nelson,"1002 Seymour St (Seymour and Nelson), Vancouve...",Vancouver,V6B 3M6,BC,NaN,NaN,NaN